name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd algorithmic-contest-platform

            sudo docker-compose down

            sudo git pull origin main

            pnpm install

            cp apps/web/.env.example apps/web/.env
            cp packages/db/.env.example packages/db/.env

            PORT=3000
              if lsof -t -i:$PORT; then
              echo "Port $PORT in use, attempting to kill process..."
              kill -9 $(lsof -t -i:$PORT)
              echo "Process killed. Waiting for port to be released..."
              sleep 5
            fi

            docker-compose up --build -d
            
            pnpm run build
            
            cd apps/web
            nohup pnpm run start &
          EOF
